### PR TITLE
Created the code of conduct markdown and environment file

### PR DESCRIPTION
**Pull request by Jing-19**
GitHub issue: #5 

Create a CODE_OF_CONDUCT.md file and environment files.

### CODE REVIEW

**Review by jokittipong — COMMENTED** [review]
Thought we don't need the r package in the environment.yaml file.
Others than that LGTM!!

**Comment by tangyl92** [comment]
Great job

**Review by tangyl92 — APPROVED** [review]

**Review by jokittipong — APPROVED** [review]
LGTM!!

**Review by hchqin — APPROVED** [review]
Looks good, thanks

**Pull request merged**
